spring:
  kafka:
    producer:
      bootstrap-servers: "kafka:29092"
      properties:
        retention.ms: 60000
        connections.max.idle.ms: 900000

---
server:
  port: 8082

---

url: "https://api.openweathermap.org/data/2.5/weather?q=Juja,ke&APPID=9a848d03f9a625b2df4e452191dde097"